"""
Django settings for deai project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
# from django.core.cache import cache
from pathlib import Path
from django import apps
from django.apps import *
import os, sys
import channels
from channels.routing import ProtocolTypeRouter 

from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = config('SECRET_KEY')
RIOT_API_KEY = config('RIOT_API_KEY')
RIOT_DD_VERSION = '16.5.1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['localhost', '127.0.0.1']
ALLOWED_HOSTS = ['*']
# ngrok HTTPS 헤더 신뢰
CSRF_TRUSTED_ORIGINS = ['https://unmasticatory-shannon-unfrosty.ngrok-free.dev']
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # ngrok/배포 시에만 활성화
# Application definition

INSTALLED_APPS = [
    #'score',
    'channels',
    "deai_project",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "riot-cache"
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'deai.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'deai_project' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'deai.wsgi.application'
ASGI_APPLICATION = 'deai.asgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}
# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL  = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # collectstatic 결과물 위치
STATICFILES_DIRS = [
    # os.path.join(BASE_DIR, 'static'),  # 원본 static 파일 위치
     BASE_DIR / 'deai_project' / 'static',
]

SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE   = False
CSRF_COOKIE_SAMESITE    = 'Lax'
CSRF_COOKIE_SECURE      = False

CSRF_TRUSTED_ORIGINS = [
    'https://unmasticatory-shannon-unfrosty.ngrok-free.dev',
    'http://unmasticatory-shannon-unfrosty.ngrok-free.dev', 
]
# 이메일 설정 (Gmail SMTP)
EMAIL_BACKEND       = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST          = 'smtp.gmail.com'
EMAIL_PORT          = config('EMAIL_PORT')
EMAIL_USE_TLS       = True
EMAIL_HOST_USER     = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')     
DEFAULT_FROM_EMAIL  = EMAIL_HOST_USER

RIOT_REGION_MAP = {
    'kr':   {'platform': 'kr.api.riotgames.com',   'regional': 'asia.api.riotgames.com'},
    'na1':  {'platform': 'na1.api.riotgames.com',  'regional': 'americas.api.riotgames.com'},
    'euw1': {'platform': 'euw1.api.riotgames.com', 'regional': 'europe.api.riotgames.com'},
    'eun1': {'platform': 'eun1.api.riotgames.com', 'regional': 'europe.api.riotgames.com'},
    'jp1':  {'platform': 'jp1.api.riotgames.com',  'regional': 'asia.api.riotgames.com'},
    'br1':  {'platform': 'br1.api.riotgames.com',  'regional': 'americas.api.riotgames.com'},
    'la1':  {'platform': 'la1.api.riotgames.com',  'regional': 'americas.api.riotgames.com'},
    'la2':  {'platform': 'la2.api.riotgames.com',  'regional': 'americas.api.riotgames.com'},
    'oc1':  {'platform': 'oc1.api.riotgames.com',  'regional': 'sea.api.riotgames.com'},
    'tr1':  {'platform': 'tr1.api.riotgames.com',  'regional': 'europe.api.riotgames.com'},
    'ru':   {'platform': 'ru.api.riotgames.com',   'regional': 'europe.api.riotgames.com'},
}

VAL_TIER_MAP = {
    0 : {'name': 'UNRANKED',   'division': ''},
    1 : {'name': 'UNRANKED',   'division': ''},
    2 : {'name': 'UNRANKED',   'division': ''},
    3 : {'name': 'IRON',       'division': '1'},
    4 : {'name': 'IRON',       'division': '2'},
    5 : {'name': 'IRON',       'division': '3'},
    6 : {'name': 'BRONZE',     'division': '1'},
    7 : {'name': 'BRONZE',     'division': '2'},
    8 : {'name': 'BRONZE',     'division': '3'},
    9 : {'name': 'SILVER',     'division': '1'},
    10: {'name': 'SILVER',     'division': '2'},
    11: {'name': 'SILVER',     'division': '3'},
    12: {'name': 'GOLD',       'division': '1'},
    13: {'name': 'GOLD',       'division': '2'},
    14: {'name': 'GOLD',       'division': '3'},
    15: {'name': 'PLATINUM',   'division': '1'},
    16: {'name': 'PLATINUM',   'division': '2'},
    17: {'name': 'PLATINUM',   'division': '3'},
    18: {'name': 'DIAMOND',    'division': '1'},
    19: {'name': 'DIAMOND',    'division': '2'},
    20: {'name': 'DIAMOND',    'division': '3'},
    21: {'name': 'ASCENDANT',  'division': '1'},
    22: {'name': 'ASCENDANT',  'division': '2'},
    23: {'name': 'ASCENDANT',  'division': '3'},
    24: {'name': 'IMMORTAL',   'division': '1'},
    25: {'name': 'IMMORTAL',   'division': '2'},
    26: {'name': 'IMMORTAL',   'division': '3'},
    27: {'name': 'RADIANT',    'division': ''},
}

VAL_QUEUE_MAP = {
    'competitive'   : '경쟁전',
    'unrated'       : '일반전',
    'spikerush'     : '스파이크 돌격',
    'deathmatch'    : '데스매치',
    'ggteam'        : '에스컬레이션',
    'hurm'          : '팀 데스매치',
    'swiftplay'     : '스위프트 플레이',
    'onefa'         : '복제 요원',
    'snowballfight' : '스노우볼 파이트',
    'newmap'        : '신규 맵',
    ''              : '커스텀',
}

VAL_MAP_MAP = {
    '/Game/Maps/Ascent/Ascent'              : 'Ascent',
    '/Game/Maps/Bind/Duality'               : 'Bind',
    '/Game/Maps/Blast/Blast'                : 'Breeze',
    '/Game/Maps/Canyon/Canyon'              : 'Fracture',
    '/Game/Maps/Foxtrot/Foxtrot'            : 'Icebox',
    '/Game/Maps/Port/Port'                  : 'Pearl',
    '/Game/Maps/Triad/Triad'                : 'Haven',
    '/Game/Maps/Jam/Jam'                    : 'Lotus',
    '/Game/Maps/Juliett/Juliett'            : 'Sunset',
    '/Game/Maps/Pitt/Pitt'                  : 'Abyss',
    '/Game/Maps/HURM/HURM_Alley/HURM_Alley': 'District',
    '/Game/Maps/HURM/HURM_Bowl/HURM_Bowl'   : 'Kasbah',
    '/Game/Maps/HURM/HURM_Civic/HURM_Civic' : 'Drift',
    '/Game/Maps/HURM/HURM_Helix/HURM_Helix' : 'Glitch',
    '/Game/Maps/Poveglia/Range'             : 'The Range',
}

VAL_AGENT_MAP = {
    'add6443a-41bd-e414-f6ad-e58d267f4e95': 'Jett',
    'f94c3b30-42be-e959-889c-5aa313dba261': 'Phoenix',
    'eb93336a-449b-9c1b-0a54-a891f7921d69': 'Reyna',
    '7f94d92c-4234-0a36-9646-3a87eb8b5c89': 'Yoru',
    '41fb69c1-4189-7b37-f117-bcaf1e96f1bf': 'Neon',
    '0e38b510-41a8-5780-7db6-fa85e7f2d8dc': 'Iso',
    '569fdd95-4d10-43ab-ca70-79becc718b46': 'Sage',
    '707eab51-4836-f488-046a-cda6bf494859': 'Viper',
    'a09993d9-4a49-1c74-15e4-d6e6e15a6b52': 'Viper',
    '8e253930-4c05-31dd-1b6c-968525494517': 'Omen',
    '22697054-9a31-4a64-9a27-2e8cce5a4c1e': 'Omen',
    '9f0d8ba9-4140-b941-57d3-a7ad57c6b417': 'Brimstone',
    'cc8b64c8-4b25-4ff9-6e7f-37b4da43d235': 'Harbor',
    '95b78ed7-4637-86d9-7e41-71ba8c293152': 'Harbor',
    '1180e9ad-4f00-aeab-7fd0-fa7a47ef7dce': 'Clove',
    '320b2a48-4d9b-a075-30f1-1f93a9b638fa': 'Sova',
    '6f2a04ca-43e0-be17-7f36-b3908627744d': 'Skye',
    '601dbbe7-43ce-be57-2a40-4abd24953621': 'KAY/O',
    '5f8d3a7f-467b-97f3-062c-13acf203c006': 'Breach',
    '117ed9e3-49f3-6512-3ccf-0cada7e3823b': 'Cypher',
    '1e58de9c-4950-5125-93e9-a0aee9f98746': 'Killjoy',
    '1dbf2edd-4729-0984-3115-daa5eed44993': 'Chamber',
    'efba5359-4016-a1e5-7626-b1ae976551bc': 'Deadlock',
    'e370fa57-4757-3604-3648-499e1f642d3f': 'Gekko',
    'e370fa57-4757-3604-3648-499e1f642d3f': 'Gekko',
    'dade69b4-4f5a-8528-247b-219e5a1facd6': 'Neon',
    'bb2a4828-46eb-8cd1-e765-15848195d751': 'Fade',
    '2fb58c54-4f90-a7e4-3e0e-e5e7fdccabdb': 'Vyse',
}
