# Generated by Django 6.0.2 on 2026-03-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deai_project', '0013_rankingsnapshot_rankingentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOL_infoChampionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='챔피언 키(DDragon id)')),
                ('name', models.CharField(max_length=50, verbose_name='챔피언 이름')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='타이틀')),
                ('primary_class', models.CharField(max_length=20, verbose_name='주 포지션')),
                ('tags', models.JSONField(default=list, verbose_name='태그 목록')),
                ('blurb', models.TextField(blank=True, verbose_name='설명')),
                ('img_url', models.CharField(max_length=200, verbose_name='아이콘 URL')),
                ('splash_url', models.CharField(blank=True, max_length=200, verbose_name='스플래시 URL')),
                ('patch_version', models.CharField(max_length=20, verbose_name='패치 버전')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최근 갱신')),
            ],
            options={
                'verbose_name': 'LoL 챔피언 정보',
                'db_table': 'lol_info_champion',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LOL_infoItemTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(db_index=True, unique=True, verbose_name='아이템 ID')),
                ('name', models.CharField(max_length=100, verbose_name='아이템 이름')),
                ('item_type', models.CharField(choices=[('legendary', '레전더리'), ('arena_legendary', '아레나 레전더리'), ('arena', '아레나 전용'), ('aram', '칼바람 전용'), ('entry', '중간/기본 아이템')], max_length=20, verbose_name='아이템 종류')),
                ('stats', models.CharField(blank=True, max_length=300, verbose_name='스탯 텍스트')),
                ('stats_detail', models.JSONField(default=dict, verbose_name='스탯 상세 (dict)')),
                ('desc', models.CharField(blank=True, max_length=200, verbose_name='짧은 설명')),
                ('full_desc', models.TextField(blank=True, verbose_name='전체 설명')),
                ('gold', models.IntegerField(default=0, verbose_name='구매 가격')),
                ('gold_sell', models.IntegerField(default=0, verbose_name='판매 가격')),
                ('img_url', models.CharField(max_length=200, verbose_name='아이콘 URL')),
                ('from_ids', models.JSONField(default=list, verbose_name='조합 재료 ID 목록')),
                ('into_ids', models.JSONField(default=list, verbose_name='합성 결과 ID 목록')),
                ('patch_version', models.CharField(max_length=20, verbose_name='패치 버전')),
                ('mapping_hash', models.CharField(default='', max_length=8, verbose_name='매핑 해시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최근 갱신')),
            ],
            options={
                'verbose_name': 'LoL 아이템 정보',
                'db_table': 'lol_info_item',
                'ordering': ['item_type', '-gold'],
            },
        ),
        migrations.CreateModel(
            name='TFT_infoChampionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(db_index=True, max_length=80, unique=True, verbose_name='apiName (CDragon)')),
                ('name', models.CharField(max_length=50, verbose_name='챔피언 이름')),
                ('cost', models.PositiveSmallIntegerField(verbose_name='코스트')),
                ('traits', models.JSONField(default=list, verbose_name='시너지 목록')),
                ('img_url', models.CharField(blank=True, max_length=300, verbose_name='아이콘 URL')),
                ('set_number', models.PositiveSmallIntegerField(default=16, verbose_name='시즌 세트 번호')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최근 갱신')),
            ],
            options={
                'verbose_name': 'TFT 챔피언 정보',
                'db_table': 'tft_info_champion',
                'ordering': ['cost', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TFT_infoItemTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='apiName (CDragon)')),
                ('name', models.CharField(max_length=100, verbose_name='아이템 이름')),
                ('item_type', models.CharField(choices=[('component', '기본 부품'), ('combined', '조합 아이템'), ('radiant', '찬란한 아이템'), ('emblem', '시너지 상징'), ('artifact', '아티팩트')], max_length=20, verbose_name='아이템 종류')),
                ('stats', models.CharField(blank=True, max_length=300, verbose_name='스탯 텍스트')),
                ('desc', models.TextField(blank=True, verbose_name='설명')),
                ('img_url', models.CharField(blank=True, max_length=300, verbose_name='아이콘 URL')),
                ('comp', models.JSONField(default=list, verbose_name='조합 재료')),
                ('trait_name', models.CharField(blank=True, max_length=50, verbose_name='시너지 이름 (emblem)')),
                ('trait_icon', models.CharField(blank=True, max_length=300, verbose_name='시너지 아이콘 (emblem)')),
                ('set_number', models.PositiveSmallIntegerField(default=16, verbose_name='시즌 세트 번호')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최근 갱신')),
            ],
            options={
                'verbose_name': 'TFT 아이템 정보',
                'db_table': 'tft_info_item',
                'ordering': ['item_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TFT_infoSynergeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='apiName (CDragon)')),
                ('name', models.CharField(max_length=50, verbose_name='시너지 이름')),
                ('desc', models.TextField(blank=True, verbose_name='시너지 설명')),
                ('icon_url', models.CharField(blank=True, max_length=300, verbose_name='아이콘 URL')),
                ('tiers', models.JSONField(default=list, verbose_name='발동 단계')),
                ('set_number', models.PositiveSmallIntegerField(default=16, verbose_name='시즌 세트 번호')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최근 갱신')),
            ],
            options={
                'verbose_name': 'TFT 시너지 정보',
                'db_table': 'tft_info_synerge',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VAL_infoAgentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_uuid', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='에이전트 UUID')),
                ('name', models.CharField(max_length=50, verbose_name='에이전트 이름')),
                ('role', models.CharField(blank=True, choices=[('duelist', '듀얼리스트'), ('initiator', '개시자'), ('controller', '컨트롤러'), ('sentinel', '파수꾼')], max_length=20, verbose_name='역할군')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('portrait_url', models.CharField(blank=True, max_length=300, verbose_name='포트레이트 URL')),
                ('icon_url', models.CharField(blank=True, max_length=300, verbose_name='아이콘 URL')),
                ('abilities', models.JSONField(default=list, verbose_name='스킬 목록')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최근 갱신')),
            ],
            options={
                'verbose_name': 'Valorant 에이전트 정보',
                'db_table': 'val_info_agent',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Val_infoGunTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gun_uuid', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='총기 UUID')),
                ('name', models.CharField(max_length=50, verbose_name='총기 이름')),
                ('category', models.CharField(blank=True, choices=[('sidearm', '보조무기'), ('smg', 'SMG'), ('rifle', '소총'), ('sniper', '저격총'), ('shotgun', '샷건'), ('heavy', '중화기'), ('melee', '근접무기')], max_length=20, verbose_name='카테고리')),
                ('cost', models.IntegerField(default=0, verbose_name='가격')),
                ('fire_rate', models.FloatField(default=0, verbose_name='연사속도')),
                ('magazine_size', models.IntegerField(default=0, verbose_name='탄창')),
                ('damage_ranges', models.JSONField(default=list, verbose_name='데미지 정보')),
                ('icon_url', models.CharField(blank=True, max_length=300, verbose_name='아이콘 URL')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최근 갱신')),
            ],
            options={
                'verbose_name': 'Valorant 총기 정보',
                'db_table': 'val_info_gun',
                'ordering': ['category', 'cost'],
            },
        ),
    ]
