# Generated by Django 6.0.2 on 2026-03-26 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deai_project', '0014_lol_infochampiontable_lol_infoitemtable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Riot_UserINFO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puuid', models.CharField(db_index=True, max_length=120, unique=True, verbose_name='PUUID')),
                ('username', models.CharField(db_index=True, max_length=40, verbose_name='게임 이름 (gameName)')),
                ('tag', models.CharField(max_length=10, verbose_name='태그 라인 (#tagLine)')),
                ('region', models.CharField(default='kr', max_length=10, verbose_name='지역 (kr / na / euw …)')),
                ('last_searched_at', models.DateTimeField(auto_now=True, verbose_name='마지막 조회 시각')),
            ],
            options={
                'verbose_name': 'Riot 유저 정보 캐시',
                'db_table': 'riot_user_info',
            },
        ),
        migrations.CreateModel(
            name='Riot_MatchInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('lol', 'League of Legends'), ('tft', 'Teamfight Tactics'), ('val', 'Valorant')], max_length=5, verbose_name='게임 종류')),
                ('queue_type', models.CharField(choices=[('lol_ranked_solo', 'LoL 솔로랭크'), ('lol_ranked_flex', 'LoL 자유랭크'), ('lol_normal', 'LoL 일반'), ('lol_aram', 'LoL 칼바람'), ('lol_urf', 'LoL 우르프'), ('lol_arena', 'LoL 아레나'), ('tft_ranked', 'TFT 솔로랭크'), ('tft_double_up', 'TFT 더블업'), ('tft_normal', 'TFT 일반'), ('val_competitive', 'Valorant 경쟁전'), ('val_unrated', 'Valorant 일반(비경쟁)'), ('val_spike_rush', 'Valorant 스파이크 러쉬'), ('val_deathmatch', 'Valorant 데스매치'), ('val_team_deathmatch', 'Valorant 팀 데스매치')], max_length=25, verbose_name='큐 타입')),
                ('last_match_id', models.CharField(blank=True, default='', max_length=30, verbose_name='최근 매치 ID')),
                ('cached_data', models.JSONField(blank=True, default=dict, verbose_name='캐시 데이터 (JSON)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최근 갱신')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_infos', to='deai_project.riot_userinfo', verbose_name='Riot 유저')),
            ],
            options={
                'verbose_name': 'Riot 전적 캐시',
                'db_table': 'riot_match_info',
                'indexes': [models.Index(fields=['user', 'game'], name='riot_match__user_id_b6e2b4_idx')],
                'unique_together': {('user', 'game', 'queue_type')},
            },
        ),
    ]
