# Generated by Django 6.0.2 on 2026-03-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deai_project', '0015_riot_userinfo_riot_matchinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='riot_matchinfo',
            name='last_refresh_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='마지막 전적 갱신 시각'),
        ),
        migrations.AddField(
            model_name='riot_matchinfo',
            name='match_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='전적 매치 ID 목록 (최대 20개)'),
        ),
        migrations.AddField(
            model_name='riot_userinfo',
            name='profile_icon_id',
            field=models.IntegerField(default=0, verbose_name='프로필 아이콘 ID'),
        ),
        migrations.AddField(
            model_name='riot_userinfo',
            name='summoner_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='소환사 ID (encrypted)'),
        ),
        migrations.AddField(
            model_name='riot_userinfo',
            name='summoner_level',
            field=models.IntegerField(default=0, verbose_name='소환사 레벨'),
        ),
    ]
